### ISSUE TITLE
可否支持选中文本跳转到定义？

### ISSUE THREAD

**Issue by jeremyxu2010** [xiaoxin-sky/lapce-vue#5]
RT

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xiaoxin-sky** [comment]
可以支持，这也是我下一步计划要做的。

**Comment by xiaoxin-sky** [comment]
Lapce already supports go to definition. Please download the Nightly Lpace to experience
