### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by mztlive** [xiaoxin-sky/lapce-vue#6]
在lapce里面安装后打开vue项目，无法自动完成，也不能定义跳转。。除了着色别的似乎都用不了

通过plugin market安装的

**Comment by xiaoxin-sky** [comment]
插件中需要依赖，请查看插件目录中是否下载完整

**Comment by mztlive** [comment]
> 

嗯，现在可以了。我看了源码好像是要下载lsp服务器的，多等了一会就好了。

但是有个新问题。 就是巨卡，自动完成基本上要等待2s以上才会弹出来。

m1芯片的mac, 不知道你是不是这样

**Comment by xiaoxin-sky** [comment]
> 但是有个新问题。 就是巨卡，自动完成基本上要等待2s以上才会弹出来。
你使用的什么版本的Lapce，使用release。
